void setup(){
 size(1280, 720);
 background(255);
 frameRate(1);
}

void draw(){
  drawCity();
}

void drawHouse(int xPos, int yPos, float scale, color col){
   pushMatrix(); // pushMatrix and popMatrix help reset positioning between each time a hose is drawn
   
   /*
   This is the house drawing function,
   it is generated by image_code_generator
   which is also a part of project_2
   */
   // This function's code is located in a seperate file
   GENERATED_IMAGE_08F4BB82_MONOCHROME(xPos, yPos, scale, col); 
   
   popMatrix(); //popMatrix is what resets the positioning before next draw
}

void drawBlock(int xPos, int yPos, color col){
  drawHouse(xPos, yPos, 0.1, col);
  drawHouse(xPos, yPos + 70, 0.1, col);
  drawHouse(xPos + 70, yPos, 0.1, col);
  drawHouse(xPos + 70, yPos + 70, 0.1, col);
}

void drawNeighborhood(int xPos, int yPos, color col){
  
  // The offset variable determines the spacing between blocks
  int offset = 155;
  for(int i = 0; i < 3; i++)
    for(int j = 0; j < 3; j++)
      drawBlock(xPos + i * offset, yPos + j * offset, col);
}

void drawCity(){
  
  // Here the spacing between Neighborhoods is determined by the increments
  for(int i = -350; i < width; i += 500)
    for(int j = -300; j < height; j += 500)
      drawNeighborhood(i, j, color((int)(Math.random()*200), (int)(Math.random()*200), (int)(Math.random()*200)));
}
